sudo: required
services:
  - docker

before_install:
  - docker build -t duong120798/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run duong120798/react-test -e CI=true npm run test -- --coverage

after_success:
  - docker build -t duong1200798/multi-client -f ./client/Dockerfile ./client
  - docker build -t duong1200798/multi-nginx -f ./nginx/Dockerfile ./nginx
  - docker build -t duong1200798/multi-server -f ./server/Dockerfile ./server
  - docker build -t duong1200798/multi-worker -f ./worker/Dockerfile ./worker
  # login hub.docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take those images and build to hub.docker
  - docker push duong1200798/multi-client
  - docker push duong1200798/multi-nginx
  - docker push duong1200798/multi-server
  - docker push duong1200798/multi-worker